name: machine_test_karthik
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  flutter_hooks: ^0.20.5
  http: ^1.2.2
  go_router: ^14.4.1
  get_storage: ^2.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
